ProjectCNNWebsite.UI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectCNNWebsite.Contract.ViewModels;
using ProjectCNNWebsite.Data;
using ProjectCNNWebsite.Domain;
using ProjectCNNWebsite.Services;

namespace ProjectCNNWebsite.UI.Controllers
{
   public class AdminController : Controller
   {
      // GET: Admin
      public ActionResult Index()
      {
         ViewBag.Title = "Admin Homepage";
         using (DatabaseContext databaseContext = new DatabaseContext())
         {
            var model = new AdminIndexViewModel()
            {
               NewsList = databaseContext.News.ToList(),
               Categories = databaseContext.Category.ToList()
            };
            return View(model);
         }         
      }

      public ActionResult Insert()
      {
         ViewBag.Title = "Insert News";
         return View();
      }

      public ActionResult InsertNews(News news)
      {
         using (var databaseContext = new DatabaseContext())
         {
            databaseContext.News.Add(news);
            databaseContext.SaveChanges();
         }
         return RedirectToAction("Index");
      }

   
      public ActionResult CategoryInsert(Category category)    
      {
         using (var databaseContext = new DatabaseContext())
         {
            databaseContext.Category.Add(category);
            databaseContext.SaveChanges();
         }
         return RedirectToAction("Index");
      }

      public ActionResult Delete()
      {
         ViewBag.Title = "Delete News";
         return View();
      }

      public ActionResult DeleteNews()
      {
         int id = Convert.ToInt32(Request.Form["News.Id"]);
         using (var databaseContext = new DatabaseContext())
         {
            if (id <= 0)
               throw new System.NullReferenceException("id boş olamaz");
            News news = databaseContext.News.FirstOrDefault(i => i.Id == id);
            databaseContext.News.Remove(news);
            databaseContext.SaveChanges();
         }
         return RedirectToAction("Index");
      }

      public ActionResult DeleteCategory()    
      {
         int id = Convert.ToInt32(Request.Form["Category.Id"]);
         using (var databaseContext = new DatabaseContext())
         {
            if (id <= 0)
               throw new System.NullReferenceException("id boş olamaz");
            Category category = databaseContext.Category.FirstOrDefault(i => i.Id == id);
            databaseContext.Category.Remove(category);
            databaseContext.SaveChanges();
         }
         return RedirectToAction("Index");
      }

      public ActionResult SignIn()
      {
         return View();
      }

      public ActionResult CheckIfAdminExists(string adminNickName, string adminPassword)
      {
         var databaseContext = new DatabaseContext();
         var adminList = databaseContext.Admin.ToList();
         Admin admin = new Admin
         {
            AdminNickName = adminNickName,
            AdminPassword = adminPassword
         };
         foreach (var item in adminList)
         {
            if ((item.AdminNickName == admin.AdminNickName) && (item.AdminPassword == admin.AdminPassword))
               return RedirectToAction("Index");
         }
         return View("SignIn");
         
      }

      public ActionResult InsertAdmin(Admin admin)   
      {
         using (var databaseContext = new DatabaseContext())
         {
            databaseContext.Admin.Add(admin);
            databaseContext.SaveChanges();
         }
         return View("SignIn");
      }
   }

}

ProjectCNNWebsite.UI/Controllers/EconomicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectCNNWebsite.Contract.ViewModels;
using ProjectCNNWebsite.Data;

namespace ProjectCNNWebsite.UI.Controllers
{
    public class EconomicsController : Controller
    {
      // GET: Economics
      public ActionResult Index()
      {
         ViewBag.Title = "Ekonomi Haberleri";
         using (var databaseContext = new DatabaseContext())
         {
            var model = new NewsViewModel
            {
               NewsList = databaseContext.News.ToList(),
               Categories = databaseContext.Category.ToList()
            };
            return View(model);
         }
      }
   }
}

ProjectCNNWebsite.UI/Controllers/HealthNewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectCNNWebsite.Contract.ViewModels;
using ProjectCNNWebsite.Data;

namespace ProjectCNNWebsite.UI.Controllers
{
    public class HealthNewsController : Controller
    {
      // GET: HealthNews
      public ActionResult Index()
      {
         ViewBag.Title = "Sağlık Haberleri";
         using (var databaseContext = new DatabaseContext())
         {
            var model = new NewsViewModel
            {
               NewsList = databaseContext.News.ToList(),
               Categories = databaseContext.Category.ToList()
            };
            return View(model);
         }
      }
   }
}

ProjectCNNWebsite.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectCNNWebsite.UI.Controllers
{
   public class HomeController : Controller
   {
      // GET: Home
      public ActionResult Index()
      {
         return View();
      }

      [HttpPost]
      [DisplayName("Index")]
      public ActionResult IndexPost()
      {
         return View();
      }
   }
}

ProjectCNNWebsite.UI/Controllers/LifeNewsController.cs
using System.Linq;
using System.Web.Mvc;
using ProjectCNNWebsite.Contract.ViewModels;
using ProjectCNNWebsite.Data;

namespace ProjectCNNWebsite.UI.Controllers
{
   public class LifeNewsController : Controller
   {
      // GET: LifeNews
      public ActionResult Index()
      {
         ViewBag.Title = "Yaşamdan Haberler";
         using (var databaseContext = new DatabaseContext())
         {           
            var model = new NewsViewModel 
            {
               NewsList = databaseContext.News.ToList(),
               Categories = databaseContext.Category.ToList()
            };
            return View(model);
         }         
      }
   }
}

ProjectCNNWebsite.UI/Controllers/PoliticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectCNNWebsite.Contract.ViewModels;
using ProjectCNNWebsite.Data;

namespace ProjectCNNWebsite.UI.Controllers
{
   public class PoliticsController : Controller
   {
      // GET: Politics
      public ActionResult Index()
      {
         ViewBag.Title = "Politika Haberleri";
         using (var databaseContext = new DatabaseContext())
         {
            var model = new NewsViewModel
            {
               NewsList = databaseContext.News.ToList(),
               Categories = databaseContext.Category.ToList()
            };
            return View(model);
         }         
      }
   }
}

ProjectCNNWebsite.UI/Views/Admin/Delete.cshtml
@model ProjectCNNWebsite.Contract.ViewModels.AdminDeleteViewModel

@{ 
   ViewBag.Title = "Delete News";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div class="partial-nav">
        @Html.Partial("AdminNavPartial")
    </div>

    <div>
        @using (Html.BeginForm("DeleteNews", "Admin", FormMethod.Post, new { @class = "form" }))
        {
            <h2>Delete News</h2>
            @Html.LabelFor(i => i.News.Id, new { name = "Id" })
            @Html.TextBoxFor(i => i.News.Id)
            <button type="submit">Save</button>
        }
    </div>
    <div>
        @using (Html.BeginForm("DeleteCategory", "Admin", FormMethod.Post, new { @class = "form" }))
        {
            <h2>Delete Category</h2>
            @Html.LabelFor(i => i.Category.Id, new { name = "Id" })
            @Html.TextBoxFor(i => i.Category.Id)
            <button type="submit">Save</button>
        }
    </div>

</body>
</html>

ProjectCNNWebsite.UI/Views/Admin/Index.cshtml
@using ProjectCNNWebsite.Contract.ViewModels
@model AdminIndexViewModel

@{
   ViewBag.Title = "Admin Homepage";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div class="partial-nav">
        @Html.Partial("AdminNavPartial")
    </div>

    <div class="tables">
        <table class="table">
            <thead>
                <tr>
                    <th>News Title</th>
                    <th>News Content</th>
                    <th>News Photo Path</th>
                    <th>News Category</th>
                    <th>News Category Id</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.NewsList)
                {
                    <tr>
                        <td>@item.NewsTitle</td>
                        <td>@item.NewsContent</td>
                        <td>@item.NewsPhotoPath</td>
                        <td>@item.NewsCategory.CategoryName</td>
                        <td>@item.CategoryId</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="tables">
        <table class="table">
            <thead>
                <tr>
                    <th>CategoryName</th>
                    <th>CategoryDescription</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Categories)
                {
                    <tr>
                        <td>@item.CategoryName</td>
                        <td>@item.CategoryDescription</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>

ProjectCNNWebsite.UI/Views/Admin/Insert.cshtml
@using ProjectCNNWebsite.Contract.ViewModels
@model AdminIndexViewModel

@{ 
   ViewBag.Title = "Insert News";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div class="partial-nav">
        @Html.Partial("AdminNavPartial")
    </div>

    <div>
        @using (Html.BeginForm("InsertNews", "Admin", FormMethod.Post, new { @class = "form" }))
        {
            <h2>Add News</h2>
            @Html.LabelFor(i => i.News.NewsTitle, "News Title")
            @Html.TextBoxFor(i => i.News.NewsTitle, "News Title")
            @Html.LabelFor(i => i.News.NewsContent, "News Content")
            @Html.TextBoxFor(i => i.News.NewsContent, "News Content")
            @Html.LabelFor(i => i.News.NewsPhotoPath, "News Photopath")
            @Html.TextBoxFor(i => i.News.NewsPhotoPath, "News Photopath")
            @Html.LabelFor(i => i.News.NewsCategory, "News Category")
            @Html.TextBoxFor(i => i.News.NewsCategory, "News Category")
            @Html.LabelFor(i => i.News.CategoryId, "Category ID")
            @Html.TextBoxFor(i => i.News.CategoryId, "Category ID")
            <button type="submit">Save</button>
        }
    </div>

    <div>
        @using (Html.BeginForm("CategoryInsert", "Admin", FormMethod.Post, new { @class = "form" }))
        {
            <h2>Add Category</h2>
            @Html.LabelFor(i => i.Category.CategoryName, "Category Name")
            @Html.TextBoxFor(i => i.Category.CategoryName, "Category Name")
            @Html.LabelFor(i => i.Category.CategoryDescription, "Category Description")
            @Html.TextBoxFor(i => i.Category.CategoryDescription, "Category Description")
            <button type="submit">Save</button>
        }
    </div>

    @*<form action="NewsInsert" method="post">
            <label for="newsTitle">News Title</label>
            <input type="text" placeholder="Enter news title" id="newsTitle" name="newsTitle" />
            <label for="lastName">Last Name</label>
            <input type="text" placeholder="Enter your last name" id="lastName" name="lastName" />
            <label for="dateOfBirth"></label>
            <input type="date" placeholder="Enter your birthdate" id="dateOfBirth" name="dateOfBirth" />
            <button type="submit">Submit</button>
        </form>*@
</body>
</html>

ProjectCNNWebsite.UI/Views/Admin/SignIn.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SignIn</title>
</head>
<body>
    <div> 
        @Html.Partial("AdminLogin")
    </div>
</body>
</html>

ProjectCNNWebsite.UI/Views/Economics/Index.cshtml
@using ProjectCNNWebsite.Contract.ViewModels
@model NewsViewModel

@{
    ViewBag.Title = "Ekonomi Haberleri";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @foreach (var item in Model.NewsList@*Where(i => i.CategoryId == istenen kategorideki haberleri çekmek için)*@)
{
<div class="news-content">
    <div class="news-content-text">
        <h1>@item.NewsTitle</h1>
        <p>@item.NewsContent</p>
    </div>
    <img src="@item.NewsPhotoPath" alt="@item.NewsTitle" />
</div>
}
</body>
</html>

ProjectCNNWebsite.UI/Views/HealthNews/Index.cshtml
@using ProjectCNNWebsite.Contract.ViewModels
@model NewsViewModel

@{
    ViewBag.Title = "Sağlık Haberleri";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @foreach (var item in Model.NewsList@*Where(i => i.CategoryId == istenen kategorideki haberleri çekmek için)*@)
    {
        <div class="news-content">
            <div class="news-content-text">
                <h1>@item.NewsTitle</h1>
                <p>@item.NewsContent</p>
            </div>
            <img src="@item.NewsPhotoPath" alt="@item.NewsTitle" />
        </div>
    }
</body>
</html>

ProjectCNNWebsite.UI/Views/Home/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/Content/styles/site.css" type="text/css"/>
</head>
<body>
</body>
</html>

ProjectCNNWebsite.UI/Views/LifeNews/Index.cshtml
@using ProjectCNNWebsite.Contract.ViewModels
@model NewsViewModel

@{
    ViewBag.Title = "Yaşamdan Haberler";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @*Where(i => i.CategoryId == istenen kategorideki haberleri çekmek için)*@
    @foreach (var item in Model.NewsList)
    {
        <div class="news-content">
            <div class="news-content-text">
                <h1>@item.NewsTitle</h1>
                <p>@item.NewsContent</p>
            </div>
            <img src="@item.NewsPhotoPath" alt="@item.NewsTitle" />
        </div>
    }
</body>
</html>

ProjectCNNWebsite.UI/Views/Politics/Index.cshtml
@using ProjectCNNWebsite.Contract.ViewModels
@model NewsViewModel

@{
    ViewBag.Title = "Politika Haberleri";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
        @foreach (var item in Model.NewsList@*Where(i => i.CategoryId == istenen kategorideki haberleri çekmek için)*@)
        {
            <div class="news-content">
                <div class="news-content-text">
                    <h1>@item.NewsTitle</h1>
                    <p>@item.NewsContent</p>
                </div>
                <img src="@item.NewsPhotoPath" alt="@item.NewsTitle" />
            </div>
        }
</body>
</html>

ProjectCNNWebsite.UI/Views/shared/AdminLogin.cshtml
@model ProjectCNNWebsite.Contract.ViewModels.AdminRegistrationViewModel
<div>
    @using (Html.BeginForm("CheckIfAdminExists", "Admin", FormMethod.Post, new { @class = "form" }))
    {
        @Html.LabelFor(i => i.AdminNickName,"Your Nickname", new { @for = "Nickname", }) 
        @Html.TextBoxFor(i => i.AdminNickName, new { name = "nickname" })
        @Html.LabelFor(i => i.AdminPassword, "Password", new { @for = "Password" })
        @Html.TextBoxFor(i => i.AdminPassword, new { name = "password", type = "password" })
        <button type="submit">Sign In</button>
    }
</div>

<div>
    @using (Html.BeginForm("InsertAdmin", "Admin", FormMethod.Post, new { @class = "form" }))
    {
        @Html.LabelFor(i => i.AdminFirstName, "Firstname", new { @for = "Firstname" })
        @Html.TextBoxFor(i => i.AdminFirstName, new { name = "firstname" })
        @Html.LabelFor(i => i.AdminLastName, "Lastname", new { @for = "Lastname" })
        @Html.TextBoxFor(i => i.AdminLastName, new { name = "lastname" })
        @Html.LabelFor(i => i.AdminEmailAddress, "E-mail Address", new { @for = "E-mail Address" })
        @Html.TextBoxFor(i => i.AdminEmailAddress, new { name = "emailadress", type="email" })
        @Html.LabelFor(i => i.AdminNickName, "Choose a Nickname", new { @for = "Nickname" })
        @Html.TextBoxFor(i => i.AdminNickName, new { name = "nicknameToInsert" })
        @Html.LabelFor(i => i.AdminPassword, "Set a Password", new { @for = "Password" })
        @Html.TextBoxFor(i => i.AdminPassword, new { name = "passwordToInsert", type = "password" })
        <button type="submit">Sign Up</button>
    }
</div>

ProjectCNNWebsite.UI/Views/shared/AdminNavPartial.cshtml
<ul>
    <li><a href="@Url.Action("Insert", "Admin")" class="insert-links">Add News</a></li>
    <li><a href="@Url.Action("Insert", "Admin")" class="insert-links">Add Category</a></li>
    <li><a href="@Url.Action("Delete", "Admin")" class="insert-links">Delete News</a></li>
    <li><a href="@Url.Action("Delete", "Admin")" class="insert-links">Delete Category</a></li>
    <li><a href="@Url.Action("Edit", "Admin")" class="insert-links">Edit News</a></li>
    <li><a href="@Url.Action("Edit", "Admin")" class="insert-links">Edit Category</a></li>
</ul>

ProjectCNNWebsite.UI/Views/shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" type="text/css" href="~/Content/styles/site.css" />
</head>
<body>
    <div class="container">
        <div class="header-container">
            <header class="header">
                <div class="logo">
                    <img src="~/Content/images/1-logo.jpg" alt="cnn-logo" />
                </div>
                <div class="primary-nav">
                    <ul class="nav-list">
                        <li>
                            <a href="@Url.Action("Index", "Economics")">Ekonomi</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "HealthNews")">Sağlık</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Politics")">Siyaset</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "LifeNews")">Yaşam</a>
                        </li>
                        <li>
                            <a href="@Url.Action("SignIn","Admin")">Admin</a>
                        </li>
                    </ul>
                </div>
            </header>
        </div>

        <div class="main-banner">
            <img src="~/Content/images/2-main-banner.jpg" alt="main-banner" />
        </div>

        <div class="main-content">
            @RenderBody()
        </div>

        <footer class="footer">
            <div class="social-media">
                <a href="https://tr-tr.facebook.com/" target="_blank"><img src="~/Content/images/socialmedia/Facebook.png" alt="facebook_icon" /></a>
                <a href="https://twitter.com/" target="_blank"><img src="~/Content/images/socialmedia/Twitter.png" alt="twitter_icon" /></a>
                <a href="https://www.youtube.com/" target="_blank"><img src="~/Content/images/socialmedia/YouTube.png" alt="youtube_icon" /></a>
                <a href="https://www.whatsapp.com/" target="_blank"><img src="~/Content/images/socialmedia/WhatsApp.png" alt="whatsapp_icon" /></a>
                <a href="https://www.instagram.com/?hl=tr" target="_blank"><img src="~/Content/images/socialmedia/Instagram.png" alt="instagram_icon" /></a>
                </ul>
            </div>
        </footer>
    </div>
</body>
</html>